/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.7.0 (NJsonSchema v10.6.7.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// @ts-nocheck



export interface AuthenticationResult {
  readonly isAuthenticated?: boolean;
  readonly accessToken?: string | undefined;
  readonly refreshToken?: string | undefined;
}

export interface UserDto {
  id?: number;
  firstName?: string | undefined;
  lastName?: string | undefined;
  email?: string | undefined;
  password?: string | undefined;
  role?: string | undefined;
}

export interface UserDtoListResultDto {
  data?: UserDto[] | undefined;
  count?: number;
}